# Crea la base de datos jackrabbit
- name: Comprobar si la base de datos jackrabbit existe
  postgresql_query:    
    db: "postgres"
    query: "SELECT 1 FROM pg_database WHERE datname = 'jackrabbit';"    
    login_host: "{{ POSTGRES_HOST }}"
    login_user: "{{ POSTGRES_USER }}"
    login_password: "{{ POSTGRES_PASSWORD }}"
    port: "{{ POSTGRES_PORT }}"
  register: db_jackrabbit_exists
  ignore_errors: yes

- name: Copiar el archivo JCR POSTGRESQL desde el template
  template:
    src: "bbdd/create_jcr_postgresql.sql.j2"
    dest: "/tmp/create_jcr_postgresql.sql"
  vars:
    db_jcr_password: "{{ lookup('env', 'PENTAHO_DB_JCR_PASSWORD') }}"    
  when: db_jackrabbit_exists.rowcount == 0

- name: Ejecutar el archivo JCR POSTGRESQL en la base de datos PostgreSQL remota
  become: yes
  shell: "psql -h {{ POSTGRES_HOST }} -p {{ POSTGRES_PORT }} -U {{ POSTGRES_USER }} -f /tmp/create_jcr_postgresql.sql"
  args:
    executable: /bin/bash
  environment:
    PGPASSWORD: "{{ POSTGRES_PASSWORD }}"
  when: db_jackrabbit_exists.rowcount == 0

- name: Eliminar el archivo SQL temporal
  file:
    path: "/tmp/create_jcr_postgresql.sql"
    state: absent
  