# Crea la base de datos quartz
- name: Comprobar si la base de datos quartz existe
  postgresql_query:    
    db: "postgres"
    query: "SELECT 1 FROM pg_database WHERE datname = 'quartz';"    
    login_host: "{{ POSTGRES_HOST }}"
    login_user: "{{ POSTGRES_USER }}"
    login_password: "{{ POSTGRES_PASSWORD }}"
    port: "{{ POSTGRES_PORT }}"
  register: db_quartz_exists
  ignore_errors: yes

- name: Copiar el archivo QUARTZ POSTGRESQL desde el template
  template:
    src: "bbdd/create_quartz_postgresql.sql.j2"
    dest: "/tmp/create_quartz_postgresql.sql"
  vars:
    db_quartz_password: "{{ lookup('env', 'PENTAHO_DB_QUARTZ_PASSWORD') }}"    
  when: db_quartz_exists.rowcount == 0

- name: Ejecutar el archivo quartz POSTGRESQL en la base de datos PostgreSQL remota
  become: yes
  shell: "psql -h {{ POSTGRES_HOST }} -p {{ POSTGRES_PORT }} -U {{ POSTGRES_USER }} -f /tmp/create_quartz_postgresql.sql"
  args:
    executable: /bin/bash
  environment:
    PGPASSWORD: "{{ POSTGRES_PASSWORD }}"
  when: db_quartz_exists.rowcount == 0

- name: Eliminar el archivo SQL temporal
  file:
    path: "/tmp/create_quartz_postgresql.sql"
    state: absent
  